### PR TITLE
Better hardware abstraction

### PR DESCRIPTION
**Pull request by AaronErhardt**
@crisidev this is my current WIP branch for a better hardware abstraction. It takes the [latest code from TCC's ioctl abstraction](https://github.com/tuxedocomputers/tuxedo-control-center/blob/master/src/native-lib/tuxedo_io_lib/tuxedo_io_api.hh#L336) and also adapts to the new sysfs interface of the tuxedo-keyboard driver.

The goals for sysfs is to generate a `Vec` of `led::Controllers` to manage one piece of hardware each (for example different zones on the keyboard plus the code should work with non-Tuxedo devices as well).

My goal for ioctl would be to split the interface into different traits. For example, clevo supports disabling the webcam, but uniwill doesn't. On the other side, only uniwill supports the TDP stuff (I'm not yet sure what it does though...).
In the end, we could just return `Result<Box<dyn WebcamDevice>>` and then tailord will see whether disabling the webcam is supported and will setup a DBUS service if possible. The same would work for other hardware capabilities as well.

My goal would be to rebase your branches against this even if that means a lot of conflicts.

### CODE REVIEW

**Comment by crisidev** [comment]
I'll have a look at the PR soon. I think it's better to merge this one first and adapt the work I have for Uniwill on top of this.

**Comment by crisidev** [comment]
I gave a look to the PR and it's clear to me. The HW abstraction layer is very similar to what I have still not pushed in my PR, so that's great! 

I'll try the branch and if that is ok with you, I can push directly onto this PR if I find things not working with Uniwill.

**Comment by crisidev** [comment]
I added the support for the TDP, although it is not tested because the code does not compile yet.

**Comment by crisidev** [comment]
I think I have finished the Clevo profiles support, following the same patter used in the Uniwill one.

**Comment by AaronErhardt** [comment]
I've finished the `IoInterface` struct in the `hal` module, which gives you only access to the features supported by the hardware. There are some issues with the sysfs part, but the re-enabled tests on the ioctl side seemed to work on my clevo hardware.

**Comment by crisidev** [comment]
Excellent, I'll run the tests in uniwill.

**Comment by AaronErhardt** [comment]
The sysfs stuff is now working as well. It should now detect all LED devices with reasonable color range in `/sys/class/leds` in case you have one. 

Integrating the stuff into tailord and then into the GUI will be quite interesting though. We definitely have to adapt tailord to support different amounts of fans, different amounts of led devices and varying hardware capabilities. From my perspective the easiest solution would be to keep the existing fan curve and led profile concepts and only change how they are applied.
Currently, things are relatively simple because there's just one device. I suggest we now simply use the same concept, but for multiple devices. For example, a profile (for example in `/etc/tailord/profiles/my_profile.json`) would look like this then:

```json
{
    "fans": ["my_quiet_profile", "my_second_profile", "my_quiet_profile"],
    "leds": [
        {
            "device_name": "Tuxedo keyboard",
            "profile": "my_rgb_profile"
        }
    ]
} 
```

Fan and keyboard (or rather RGB) profiles would remain unchanged.

Anyway, I'm going to sleep now, good night!

**Comment by crisidev** [comment]
Can we abstract the number of fans inside the IoInterface trait? Probably not.. Tailord will require a bit of adaptation.

In the meantime I tested and uniwill is not super snappy during consecutive set/get of fan speed, but the test passes most of the time. It looks good. I am adding a couple of things to the interface test and trying out to get the tdp status, but it return -19 in all the read call. I need to investigate. Have a good night!

**Comment by crisidev** [comment]
I have started working on tailord to ensure the new hw layer works properly. The commit also disables a bunch of things related to keyboard since coming from sysfs that are currently broken.

You can find them by searching for `TODO(clevo)`.

**Comment by crisidev** [comment]
I have https://github.com/AaronErhardt/tuxedo-rs/pull/5/commits/b3e03e6eb7f66d91871613e5ce850c0bb74eb2c4 running for a while now and it seems to handle fans properly. It sits happy without using noticeable resources printing

```
DEBUG tux_tailord::fancontrol::runtime: Current temperature is 55°C, fan speed: 37%, target fan speed: 40 fan diff: 3, fan increment 0, delay: 1.733s
...
```

The main issue I can see so far is that signals are not caught. SIGKILL of course work, but TERM and INTERRUPT do nothing. I'll try to debug this.

**Comment by crisidev** [comment]
I debugged the signal issue a little more and it only happens if the fan runtime loop is started. Could there ba a race condition that is probably triggered only by some specific hardware?

I am adding a bit of tracing to try to understand why the thread doesn't give control back.

**Comment by crisidev** [comment]
I can easily revert the last two commits if we don't want to land this amount of tracing in the code.

**Comment by AaronErhardt** [comment]
I've implemented the initial code for per device profiles. This should allow for setting different profiles for each fan or each led hardware. The code is still a bit ugly and not tested yet.

**Comment by AaronErhardt** [comment]
The latest patches don't really work on my hardware so far. I've fixed several problems, but I still something takes down the service. I assume this is caused by the DBUS connection, but I might be wrong.

**Comment by AaronErhardt** [comment]
Removing the suspend service doesn't seems to help either. Actually, zbus drops all DBUS interfaces, which drops the senders, which makes the runtime fail. But I don't understand why zbus is doing that...

**Comment by AaronErhardt** [comment]
Even if it's just reduced to the zbus code, the DBUS interfaces are still dropped. I even tried starting a regular tokio runtime without `tokio_uring` with no success. I'm starting to think this could be a zbus issue, but first I would like to reproduce this in a smaller setup.

**Comment by AaronErhardt** [comment]
Ok, seems to work now. The issue was apparently a lifetime issue I wasn't even aware it existed. I thought `_` and `_name` would be basically the same, but apparently not. Using `let _conn = ConnectionBuilder::system()...` instead of  `let _ = ConnectionBuilder::system()...` seems to have done the trick.

Let me know if it works for you as well :)

**Comment by crisidev** [comment]
It seems to be working properly, zbus is initialized and connected:

```
TRACE mio::poll: registering event source with poller: token=Token(0), interests=READABLE | WRITABLE    
 INFO start_runtime: tux_tailord: Starting tailord
TRACE start_runtime: mio::poll: registering event source with poller: token=Token(1), interests=READABLE | WRITABLE    
TRACE start_runtime: mio::poll: registering event source with poller: token=Token(2), interests=READABLE | WRITABLE    
DEBUG start_runtime: tux_tailord: Starting signal handler background loop
DEBUG start_runtime: tux_tailord: Connecting to DBUS as com.tux.Tailor
TRACE start_runtime: mio::poll: registering event source with poller: token=Token(3), interests=READABLE | WRITABLE    
DEBUG handle_signals{shutdown_sender=broadcast::Sender}: tux_tailord: Waiting for signals
TRACE start_runtime:perform: zbus::handshake: Initializing
TRACE start_runtime:perform: zbus::handshake: Waiting for DATA or OK from server
TRACE start_runtime:perform: zbus::handshake: Received OK from server
TRACE start_runtime:perform: zbus::handshake: Waiting for Unix FD passing agreement from server
TRACE start_runtime:perform: zbus::handshake: Unix FD passing agreed by server
TRACE start_runtime:perform: zbus::handshake: Handshake done
TRACE start_runtime:start_object_server{started_event=Some(Event { .. })}: zbus::connection: starting ObjectServer task
TRACE start_runtime:start_object_server{started_event=Some(Event { .. })}:{}{obj_server_task_name="ObjectServer task"}: zbus::connection: waiting for incoming method call messages..
TRACE start_runtime: zbus::connection: Sending message: Msg { type: MethodCall, path: ObjectPath("/org/freedesktop/DBus"), iface: InterfaceName(Str(Borrowed("org.freedesktop.DBus"))), member: MemberName(Str(Borrowed("Hello"))) }
TRACE start_runtime: zbus::connection: Sent message with serial: 1
TRACE socket reader: zbus::socket_reader: Waiting for message on the socket..
TRACE socket reader: zbus::socket_reader: Message received on the socket: Msg { type: MethodReturn, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 1, body: Signature("s") }
TRACE socket reader: zbus::socket_reader: Error broadcasting message to stream for `None`: SendError(..)
TRACE socket reader: zbus::socket_reader: Broadcasted to all streams: Ok(Msg { type: MethodReturn, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 1, body: Signature("s") })
TRACE socket reader: zbus::socket_reader: Waiting for message on the socket..
TRACE socket reader: zbus::socket_reader: Message received on the socket: Msg { type: Signal, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), path: ObjectPath("/org/freedesktop/DBus"), iface: InterfaceName(Str(Borrowed("org.freedesktop.DBus"))), member: MemberName(Str(Borrowed("NameAcquired"))), body: Signature("s") }
TRACE socket reader: zbus::socket_reader: Error broadcasting message to stream for `None`: SendError(..)
TRACE socket reader: zbus::socket_reader: Broadcasted to all streams: Ok(Msg { type: Signal, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), path: ObjectPath("/org/freedesktop/DBus"), iface: InterfaceName(Str(Borrowed("org.freedesktop.DBus"))), member: MemberName(Str(Borrowed("NameAcquired"))), body: Signature("s") })
TRACE socket reader: zbus::socket_reader: Waiting for message on the socket..
TRACE start_runtime: zbus::connection: Sending message: Msg { type: MethodCall, sender: UniqueName(Str(Borrowed(":1.285437"))), path: ObjectPath("/org/freedesktop/DBus"), iface: InterfaceName(Str(Borrowed("org.freedesktop.DBus"))), member: MemberName(Str(Borrowed("AddMatch"))), body: Signature("s") }
TRACE start_runtime: zbus::connection: Sent message with serial: 2
TRACE socket reader: zbus::socket_reader: Message received on the socket: Msg { type: MethodReturn, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 2 }
TRACE socket reader: zbus::socket_reader: Error broadcasting message to stream for `None`: SendError(..)
TRACE socket reader: zbus::socket_reader: Broadcasted to all streams: Ok(Msg { type: MethodReturn, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 2 })
TRACE socket reader: zbus::socket_reader: Waiting for message on the socket..
TRACE start_runtime: zbus::connection: Sending message: Msg { type: MethodCall, sender: UniqueName(Str(Borrowed(":1.285437"))), path: ObjectPath("/org/freedesktop/DBus"), iface: InterfaceName(Str(Borrowed("org.freedesktop.DBus"))), member: MemberName(Str(Borrowed("AddMatch"))), body: Signature("s") }
TRACE start_runtime: zbus::connection: Sent message with serial: 3
TRACE socket reader: zbus::socket_reader: Message received on the socket: Msg { type: MethodReturn, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 3 }
TRACE socket reader: zbus::socket_reader: Error broadcasting message to stream for `None`: SendError(..)
TRACE socket reader: zbus::socket_reader: Broadcasted to all streams: Ok(Msg { type: MethodReturn, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 3 })
TRACE socket reader: zbus::socket_reader: Waiting for message on the socket..
TRACE start_runtime: zbus::connection: Sending message: Msg { type: MethodCall, sender: UniqueName(Str(Borrowed(":1.285437"))), path: ObjectPath("/org/freedesktop/DBus"), iface: InterfaceName(Str(Borrowed("org.freedesktop.DBus"))), member: MemberName(Str(Borrowed("RequestName"))), body: Signature("su") }
TRACE start_runtime: zbus::connection: Sent message with serial: 4
TRACE socket reader: zbus::socket_reader: Message received on the socket: Msg { type: Signal, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), path: ObjectPath("/org/freedesktop/DBus"), iface: InterfaceName(Str(Borrowed("org.freedesktop.DBus"))), member: MemberName(Str(Borrowed("NameAcquired"))), body: Signature("s") }
TRACE socket reader: zbus::socket_reader: Error broadcasting message to stream for `None`: SendError(..)
TRACE socket reader: zbus::socket_reader: Broadcasted to all streams: Ok(Msg { type: Signal, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), path: ObjectPath("/org/freedesktop/DBus"), iface: InterfaceName(Str(Borrowed("org.freedesktop.DBus"))), member: MemberName(Str(Borrowed("NameAcquired"))), body: Signature("s") })
TRACE socket reader: zbus::socket_reader: Waiting for message on the socket..
TRACE socket reader: zbus::socket_reader: Message received on the socket: Msg { type: MethodReturn, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 4, body: Signature("u") }
TRACE socket reader: zbus::socket_reader: Error broadcasting message to stream for `None`: SendError(..)
TRACE socket reader: zbus::socket_reader: Broadcasted to all streams: Ok(Msg { type: MethodReturn, sender: UniqueName(Str(Borrowed("org.freedesktop.DBus"))), reply-serial: 4, body: Signature("u") })
TRACE socket reader: zbus::socket_reader: Waiting for message on the socket..
TRACE start_runtime:get_fan_speed_percent{fan=0}: tuxedo_ioctl::hal::uniwill: Fan 0 speed percentage is 30, fan speed raw: 60
TRACE start_runtime:get_fan_temperature{fan=0}: tuxedo_ioctl::hal::uniwill: Fan 0 temperature is 51 C
TRACE start_runtime:set_fans_auto: tuxedo_ioctl::hal::uniwill: Set fan mode to auto
DEBUG start_runtime: tux_tailord: Starting wait_for_suspend() background loop
DEBUG start_runtime: tux_tailord: Starting keyboard background loop
DEBUG start_runtime: tux_tailord: Starting fans background loop
 INFO start_runtime: tux_tailord: Tailord started
```

Unfortunately on my installation it is still not able to react to SIGTERM, SIGINT and SIGQUIT. What happens if you issue `killall -TERM tux-tailord`? On my system nothing, the signal handler is not called.

**Comment by crisidev** [comment]
Yeah, the signal handler is waiting, but somehow is never woken up on my system. I am having trouble debug this.

**Comment by crisidev** [comment]
> sudo killall -TERM tailord works just fine for me. Note that I renamed the executable to just tailord.

Oh I am sorry, I was running the old daemon. It works now, with signals and everything. I'll test this out for a bit and check the code. Nice work.

**Comment by crisidev** [comment]
Can you share an example of your config maybe? I am curious to see if I built something that makes sense..

**Comment by AaronErhardt** [comment]
The default config looks like this: https://github.com/AaronErhardt/tuxedo-rs/blob/ca55da4ac66f61310fe075a02450b48c953510c7/tailord/default_configs/profiles/default.json

For each fan, you just add the profile name to the list in the JSON file. Led control is a bit more difficult because you need the device id to specify the profile. I'm working on adding support to the GUI to make this easier.

**Comment by crisidev** [comment]
Thanks. My laptop has only fan support and I am still trying to understand what this TDP device is about :)

Do you want to add more things to this PR?

**Comment by AaronErhardt** [comment]
No, I think the PR is already large enough :sweat_smile: 

If we want to add more features, I would do this in separate PRs.

**Comment by crisidev** [comment]
LGTM

**Comment by AaronErhardt** [comment]
GUI is updated, let's merge this and add more fixes and features later. Thanks a lot for your support!

**Pull request merged**
