### PR TITLE
hwcaps: Add new crate for checking hardware capabilities

### PR DESCRIPTION
**Pull request by AaronErhardt**
Test with

```bash
cargo install tailor_hwcaps --git https://github.com/AaronErhardt/tuxedo-rs.git --branch hwcaps
```

### CODE REVIEW

**Comment by AaronErhardt** [comment]
@mrcjkb do I need to add something more to get this crate recognized by the existing release infrastructure? I've updated the release-please config, but not [.release-please-manifest.json](https://github.com/AaronErhardt/tuxedo-rs/blob/main/.release-please-manifest.json).

**Comment by mrcjkb** [comment]
> @mrcjkb do I need to add something more to get this crate recognized by the existing release infrastructure? I've updated the release-please config, but not [.release-please-manifest.json](https://github.com/AaronErhardt/tuxedo-rs/blob/main/.release-please-manifest.json).

Yes, I think you need to update the manifest, too, with the initial version.

**Comment by AaronErhardt** [comment]
The [flake update](https://github.com/AaronErhardt/tuxedo-rs/pull/39) did not fix the CI btw. I'm not even sure what is reported in the error...

**Comment by mrcjkb** [comment]
> The [flake update](https://github.com/AaronErhardt/tuxedo-rs/pull/39) did not fix the CI btw. I'm not even sure what is reported in the error...

Based on the log it looks like `rustfmt` is complaining.

**Comment by AaronErhardt** [comment]
My bad. I ran `cargo fmt`, but just in a subdirectory...
Should work now.

Thanks for your help!

**Pull request merged**
