### PR TITLE
Fanctrl

### PR DESCRIPTION
**Pull request by AaronErhardt**

### CODE REVIEW

**Comment by AaronErhardt** [comment]
@n-tux-tmp I've started working on this project again and pulled in your patches (I hope that's ok for you). Thanks for your work, it really helps me!

I will probably adjust the code to run from within the tailord service (so you can use DBUS from user space for configuration).

**Comment by n-tux-tmp** [comment]
Hi,

Sorry for my lack of responsiveness, and thanks for your work on this project!

Unfortunately I don’t believe I’ll have enough time to continue my work on fancontrol for now, maybe in a few months. I’m still using it on a daily basis and spotted a few issues ([I listed them here](https://git.42l.fr/neil/tuxedo-fancontrol/issues)).

I’m glad you could make some use of my code! Feel free to reuse it, it’s GPLv2.

**Comment by AaronErhardt** [comment]
No worries, I've been absent from this project for several months as well. I hope I can integrate fanctrl into tailord over the next days as this is the only reason I still have tccd running on my system. I'll also have a look at the issues :)

**Comment by AaronErhardt** [comment]
@n-tux-tmp things should now work with tailord including fancontrol (I've greatly simplified the algorithm btw.) and a new dbus interface. The new config structure is the following:

```
/etc/tailord
├── fan         # Put in the fan configs here
│   └── default.json
├── keyboard    # Put in the keyboard color configs here
│   └── default.json
└── profiles    # Put in the global configs here
    ├── active_profile.json -> default.json
    └── default.json
```

Keyboard and fan have their own specific profiles. There are also "global" profiles that point to one fan profile and one keyboard profile. This makes it easier to avoid duplication: You might want to always use the same keyboard colors but vary the fan profiles for example. To do this, you can just use the same keyboard profile name from different global profiles.

You can change the active global profile by pointing the "active_profile.json" symlink to the right profile (or use the DBUS interface for convenience).

One all changes are done, just send a reload event via DBUS (with D-Feet for example) and the new config will be loaded (`systemctl restart tailord` will work too).

But also keep in mind that this is still quite experimental :sweat_smile:

**Pull request merged**
