### PR TITLE
Add tested hardware

### PR DESCRIPTION
**Pull request by nicos68**
I tested the project on my Infinity Book S 14 gen 6 (from 2019) and can confirm it works.

### CODE REVIEW

**Comment by nicos68** [comment]
What distro are you running ? Do you also have [this](https://github.com/AaronErhardt/tuxedo-rs/issues/36) issue ?

**Comment by signaleleven** [comment]
NixOS, and no, it seems to be working fine, and the fan speed reacts to the fan profile I set, at least it looks like it. 
TCC had the option to disable and limit the clock of single cores, while I can't seem to do with this, but other than this (expected) difference it seems to work.

**Comment by AaronErhardt** [comment]
I think it would be interesting to add a small binary crate for checking hardware capabilities, for example "tailor-hwcaps". This crate could run some basic checks and print the information in a simple format, so we can address future issues easier. This should also help with resolving #36, because so far this matter has been rather confusing...

**Comment by nicos68** [comment]
FYI I have silently been doing tests on this is issue on my side and will have interesting info to share in the coming days.

**Comment by AaronErhardt** [comment]
I've added a small binary for checking your devices capabilities as I suggested earlier: #37

If you want you both could install it and share the output here so we can compare:

```sh
cargo install tailor_hwcaps --git https://github.com/AaronErhardt/tuxedo-rs.git --branch hwcaps
```

**Comment by nicos68** [comment]
So since #36 is closed I'd say this can be merged, can't it ?

**Comment by nicos68** [comment]
here is my result :
```
[OK]    Module version: "0.3.9\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
[OK]    Device interface ID: "clevo_acpi\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
[ERR]   Model ID: NotAvailable
[OK]    Available ODM performance profiles: ["quiet", "power_saving", "entertainment", "performance"]
[OK]    Default ODM performance profile: "performance"
[OK]    Number of fans: 1
[OK]    Fan temperatures [°C]: [51]
[OK]    Fan speeds [%]: [23]
[OK]    Fan min speed [%]: 20
[OK]    Webcam enabled: true
[INFO]  TDP control is not available
[OK]    Number of LED devices: 1
[OK]    LED device number: 0
[OK]    LED device name: "platform:tuxedo_keyboard"
[OK]    LED device function: "kbd_backlight"
[OK]    LED mode: Monochrome
[OK]    LED device color: Ok(Color { r: 0, g: 0, b: 0 })
```

**Comment by AaronErhardt** [comment]
Yes, let's merge this. Thanks!

**Pull request merged**
