### PR TITLE
Support Uniwill hardware

### LINKED ISSUE #3: Support uniwill hardware
Related to #2.

Since I have a Pulse 14 Gen 1, based on uniwill, I'll be working on a PR to support this hw family.

I have already something that is able to print the fan speed, so it's all downhill from here :)

### PR DESCRIPTION
**Pull request by crisidev**
## Description
I have a Pulse 15 Gen 1, based on Uniwill hardware. There are several differences with Clevo, for example I believe the keyboard backlight is just not supported as my laptop lacks RGB.

The PR cannot be merged until the following is done (this will be an ongoing list I think):
[x] Implement HW detection
[ ] Support properly all the sysfs interface
[ ] Support properly all the ioctl interface
[ ] Disable the keyboard backlight subsystem

Bugs introduced:
[ ] Why signals are ignored with the uniwill patch?
[ ] Every now and then the fan goes completely silent for a couple of seconds before restarting

This PR should close #3.

### CODE REVIEW

**Comment by AaronErhardt** [comment]
Thanks for the PR! 

Btw. I have a WIP version of tuxedo_keyboard that uses the new sysfs interface of the latest driver (since 3.2.0) which also makes hardware detection better in general. Also, I'm trying to find a better abstraction for ioctl as well, taking inspiration from your code and the tccd C++ headers.

If you give me a few hours, I can post those patches and we can work together on integrating them into tailord.

**Comment by crisidev** [comment]
Nice. I am also doing a refactoring of the ioctl to have a trait that gives the io interface and separate implementation of Clevo and Uniwill variants. I'll hold on until your patches land and integrate / test what I have 😁

**Comment by crisidev** [comment]
This pr is also still very broken, I realized most of the ioctl for unwill are user wrongly.

**Comment by crisidev** [comment]
Closed in favour of #5

**Pull request closed without merging**
