### PR TITLE
fix(tailor_gui): Make fan graph colors more robust

### PR DESCRIPTION
**Pull request by AaronErhardt**

### CODE REVIEW

**Comment by mrcjkb** [comment]
@AaronErhardt looks like the automated release PR action failed. 

I think it requires PRs to be squash-merged, so that the resulting commit message fits conventional commits.

**Comment by AaronErhardt** [comment]
[From the release please README](https://github.com/googleapis/release-please#whats-a-release-pr):

> Both squash-merge and merge commits work with Release PRs.

So according to release-please, both should work. The error is quite confusing though.
Yet, I will squash the next PR to see whether that fixes the problem.

**Comment by mrcjkb** [comment]
:thinking: Based on [this issue](https://github.com/google-github-actions/release-please-action/issues/326), maybe a retry is enough?

**Comment by AaronErhardt** [comment]
Nope, the workflow failed again. The action seems to fail consistently. I think it's rather related to https://github.com/google-github-actions/release-please-action/issues/795

**Pull request merged**
